### ISSUE TITLE
[Utility] DSL For end-to-end testing

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#126]
_* Requirments for this are still a WIP_

# Objective
Create a DSL for scripting end-to-end tests.

# Origin Document
We want to be able to easily simulate pre-defined "user flows" or "user stories" as well as enable end-to-end fuzzing.

This ticket tracks the first iteration of such a framework.

For example, one potential solution to this could involve the use of [Cucumber and Gherkin](https://cucumber.io/docs/gherkin/).

# Goals / Deliverables
- [ ] Research frameworks or libraries that can be leveraged for scripting end-to-end tests.
    - This should be timeboxed to one day and json can be used if this is not done
- [ ] Define & document the specification of the format, actors and operations this DSL will provide
- [ ] Implement the specification to support the base functionality (stake/unstake/send/etc) operations a protocol actor would want to do

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

# Non-goals
- Add new functionality to the utility module
- A complete "final" implementation of such a framework
- Automation of scripts using this DSL
- Fuzzing of scripts using this DSL

# Testing Methodology
- [ ] A new testing framework
- [ ] **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
Remove

---

Creator: @Olshansk 
Co-Owners: @andrewnguyen22 @okdas

**Comment by iajrz** [comment]
I think Gherkin+Cucumber will do the trick, because it would allow us to build our DSL from a solid base.

Gherkin works by having collections of steps that map to code, thus linking a natural language description to functionality; it gives us a parser, interpreter, tooling, and part of our language. The steps we design are the other part of our language.

For instance, in e2e testing we need to check that some cli invocations of the executable react by adequately erroring out. These three steps help us cover any such scenario:

We have a step that provides an executable from the checked out code:
```gherkin
Given the user has the current version of pocket
```

A step that runs any command via the provided executable (capturing its stdout and stderr under the hood):
```gherkin
When the user runs the command "command"
```

And a step to check the contents of the captured stderr:
```gherkin
Then the user should be able to see error containing "error message"
```

The second and third steps are implemented parametrically, so "command" and "error message" are placeholders.

I want to illustrate with an example, given the steps I mentioned above. Say we add a mystery command to pocket and decide that including a `_` or a `/` as part of a parameter should produce an error. We then think through the different ways we want to test it. Let's choose the specific scenario of rejecting bad parameters, which can be checked with the steps we have defined above.

```gherkin
Scenario Outline: Mystery Command Rejects Bad Data
Given the user has the current version of pocket
When the user runs the command <command>
Then the user should be able to see error containing "invalid character"
Examples:
|command                                                 |
|mystery "_"                                             |
|mystery "/"                                             |
|mystery "this is a valid argument, except it contains/_"|
```

And given the steps have already been implemented to test other scenarios, we're done. This is not hypothetical and would work verbatim in the current e2e suite.

New steps are meant to be added only when we need to test in novel ways.

To keep with this example: when we build the "positive" scenarios that check having proper parameters should output a success message of some sort, we'll need to add a step that is capable of examining the stdout of the command.

Step suites are easy to grow organically; adding new steps doesn't need to break old steps. If we add an unimplemented step, it's reported as "undefined" by cucumber without breaking anything. We can define the missing steps and grow the ~step suite~ language organically and in collaboration with whomever thinks up new ways to poke at or observe the system.

**Comment by Olshansk** [comment]
Superseded by #466.
