### ISSUE TITLE
[TECHDEBT] [P2P] P2P integration with utility for addressBook lookups

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#270]
## Objective

Tend for the TODO

```go
// CLEANUP(drewsky): These functions will turn into more of a "ActorToAddrBook" when we have a closer
// integration with utility.
```

## Origin Document

**Techdebt** week emphasizes code health. Particularly, removing all `placeholder` and `hacky` code. 

The past few months, `shared/modules` have built up quite a few TODOs. 

The PR should remove all `non-blocked` TODOs

## Goals

- [ ] Address tech debt

## Deliverable

- [ ] Rename ValidatorMapToNetworkPeer to ActorMapToNetworkPeer or ActorsToNetworkPeer
- [ ] Look into the changing the interface call from ConsensusModule.ValidatorMap() to PersistenceModule.GetActorsAtHeight() because all the staked protocol level actors can help in broadcasting messages.

## Non-goals / Non-deliverables

- 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
The action item for this ticket is:

1. Rename `ValidatorMapToNetworkPeer` to `ActorMapToNetworkPeer` or `ActorsToNetworkPeer`

2. Look into the changing the interface call from `ConsensusModule.ValidatorMap()` to `PersistenceModule.GetActorsAtHeight()` because all the staked protocol level actors can help in broadcasting messages.

@andrewnguyen22 Do you think we should only have validators participating in RainTree or any protocol level actor that stakes.
