### ISSUE TITLE
[DOCUMENT] Add README.md to the Consensus Module

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#335]
## Objective

Document Consensus module background, origin document, usage, how to build, how to use, code organization, and any other internals with `README.md`

## Origin Document

This is a standard for all `pocket` modules in the repository that Consensus is not excepted from. 

**Hint**: Checkout the `README.md` in other modules for examples.

## Goals

- Better document the consensus module

## Deliverable

- Add a comprehensive `README.md` to the Consensus module

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @andrewnguyen22

**Comment by Olshansk** [comment]
This one is on me, so I'll take it on that others can edit/build on.

**Comment by jessicadaugherty** [comment]
@Olshansk share mermaid.js with @gokutheengineer

**Comment by Olshansk** [comment]
> @Olshansk share mermaid.js with @gokutheengineer

Not much to share since we need to create new ones for consensus, but here are a few links I use to help me out:

- I personally use [mermaid.live](https://mermaid.live/) to make them (though notion and markdown editors have support for it too)
- For an example of how we use it, check this out: https://github.com/pokt-network/pocket/blob/main/shared/docs/PROTOCOL_STATE_HASH.md
- Documentation for details can be found here: https://mermaid-js.github.io/mermaid/#/
- You can sometimes even use [ChatGPT](https://chat.openai.com/chat) with "Provide mermaid syntax for ... " as a way to bootstrap a foundation that you edit manually

**Comment by Olshansk** [comment]
@gokutheengineer As I was working on https://github.com/pokt-network/pocket/pull/404 to improve logs, clean up some code, and uncover some inconsistencies, I realized that our flow for "who/when" should validate each message is a bit messy.

As we're thinking about a README for consensus, I think a flow similar to this would be very useful:
https://github.com/pokt-network/pocket/blob/main/shared/docs/PROTOCOL_STATE_HASH.md#block-application

E.g. Validate height -> validate round -> validate header -> validate signature -> etc...

**Comment by jessicadaugherty** [comment]
Note to define range for consensus tests

**Comment by Olshansk** [comment]
> Note to define range for consensus tests

The goal here is to just add a TODO/comment (or a starting point) for an attack taxonomy on HotPOKT core consensus.
