### ISSUE TITLE
[CODE HEALTH] Remove unused / deprecated interface functions in the `Consensus Module`

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#336]
## Objective

Cleanup deprecated / unused functions in the `Consensus Module` and sub packages (ex. `Leader_Election` & `VRF`)

Examples of unused / deprecated functions:

```
func (m *leaderElectionModule) GetModuleName() string {
	return LeaderElectionModuleName
}
```

## Origin Document

As we move fast and break interfaces, skeleton code gets left behind. The core team needs to maintain a quality standard of all modules with Code Health for a lower cognitive load for external contributors.

## Goals

- Clean `Consensus Module` of deprecated / unused functions

## Deliverable

- Code complete implementation
- `a negative` code diff

## Non-goals / Non-deliverables

- Tackling other `TODOs`

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @andrewnguyen22

**Comment by gokutheengineer** [comment]
_Some_ unused functions, such as the one in the issue definition `GetModuleName()`,  are needed because ConsensusModule interface implements the `InitializableModule`, which is defined as:

```
type InitializableModule interface {
	GetModuleName() string
	Create(runtime RuntimeMgr) (Module, error)
}
```

Therefore, to remove such functions we need to modify consensus module interface and what it implements, or change the common interface definitions such as `InitializableModule` that are used by different modules. @Olshansk what are your thoughts on this?

**Comment by gokutheengineer** [comment]
Other such unused functions that are needed due to imported interfaces:

from Module/InitializableModule interface:
```
	GetModuleName() string
	Stop() error
```

from ConfigurableModule interface:
```	
	ValidateConfig(Config) error
```


from KeyHolderModule interface:
```	
	GetPrivateKey() (crypto.PrivateKey, error)
```

**Comment by Olshansk** [comment]
> Therefore, to remove such functions we need to modify consensus module interface and what it implements, or change the common interface definitions such as InitializableModule that are used by different modules. @Olshansk what are your thoughts on this?

The only place in the code where we use `.GetModuleName())` is here: https://github.com/pokt-network/pocket/blob/a53a10436a91ea5f3fc55911e5b66594c9311fb8/logger/module.go#L100

```go
func (m *loggerModule) InitLogger() {
	m.logger = m.CreateLoggerForModule(m.GetModuleName())
}
```

In short, it is how we're going to enable observability to automatically affix the module (and eventually other info) that logs came from, which is why we need to keep it.

Side note: If you add `go` above the backticks in markdown, it adds syntax highlighting in place:

<img width="390" alt="Screenshot 2022-12-12 at 5 16 02 PM" src="https://user-images.githubusercontent.com/1892194/207202532-844055ff-b378-4429-be87-9d6c1b33ad65.png">

**Comment by Olshansk** [comment]
Re `ValidateConfig` - we have an empty placeholder for it, but it is used in the consensusModule's `Create`

```go
func (*consensusModule) Create(runtimeMgr modules.RuntimeMgr) (modules.Module, error) {
	var m *consensusModule

	cfg := runtimeMgr.GetConfig()
	if err := m.ValidateConfig(cfg); err != nil {
		return nil, fmt.Errorf("config validation failed: %w", err)
	}
```

Did you mean that we don't need them at all?

**Comment by gokutheengineer** [comment]
> In short, it is how we're going to enable observability to automatically affix the module (and eventually other info) that logs came from, which is why we need to keep it.

Okay, that makes sense, and I understand why they are useful to us. 


> Did you mean that we don't need them at all?

No, I don't mean that we don't need them at all. What I wanted to underline that they are not "active and functioning" in the current stage of the code.  As you explained in your previous comment, now it is clear for `ValidateConfig ` and `GetModuleName`. So at this point, I think there is no value or meaning to try to remove interface functions as defined in the issue, because they are either placeholders, or will be useful even if they are not implemented fully yet. 

However, I will check other unused functions in overall consensus, without limiting the scope to the interface functions as defined in this issue. We can continue on this issue, or if you prefer and agree we can close this one and open a new issue for this.

**Comment by Olshansk** [comment]
> So at this point, I think there is no value or meaning to try to remove interface functions as defined in the issue, because they are either placeholders, or will be useful even if they are not implemented fully yet.

I think we have TODOs / comments in some places. The takeaway here is that we should add these for all interim placeholders we add.

> However, I will check other unused functions in overall consensus, without limiting the scope to the interface functions as defined in this issue. We can continue on this issue, or if you prefer and agree we can close this one and open a new issue for this.

Since you are already looking, reading and understanding the Consensus module, let's use this ticket to identify other functions we could (if need be) remove. If you don't find anything, we can just close this out.

My guess it that VSCode (or some go linter) can potentially do this automatically for us, but I haven't investigated this.

**Comment by Olshansk** [comment]
Closing out outdated ticket as the code has significantly changed since this.
