### ISSUE TITLE
[Client Tooling] Keybase

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#455]
## Objective

Miniature Keybase MVP functionality that allows accounts to interact with keys (e.g. import, create, export, etc...) 

## Origin Document

[V1 Roadmap: M1 Proof of Stake](https://github.com/pokt-network/pocket/milestone/7)

In order to achieve the M1 milestone - a mini-keybase implementation is needed to enable dynamic accounts and actors.

This keybase may be used for the following tasks:

- Signing blocks
- Signing transactions
- Signing arbitrary messages
- Signing multi-sig messages

### Research Resources

If you are unfamiliar with keybases you can gain high level context by reviewing these API specifications:
- https://keybase.io/docs/api/1.0
- https://keybase.io/docs/api/1.0/call/key/add

Key management exists as part of Pocket V0. It is recommended to install the CLI to see what commands exist as part of key management today. It's also recommended to review the current keybase implementation in the codebase.
- [Installing the Pocket-Core CLI](https://github.com/pokt-network/pocket-core/tree/staging/doc/specs/cli)
- [keys.go](https://github.com/pokt-network/pocket-core/blob/staging/crypto/keys.go)

As V0 is a ~2 yr old project, it is recommended to compare existing functionality against the latest industry standards to look for opportunities to modernize or enhance how keys are managed in V1
- [Ignite](https://github.com/ignite/cli/search?q=keybase) is using [Cosmos](https://github.com/cosmos/cosmos-sdk/tree/main/client/keys)

It's recommend that the assignee borrows what works from the above resources and integrates it with Pocket-specific utility.

### Technical Requirements

- Please use /shared/crypto/ed25519 as the PK Library
- Please use a filesystem.db for implementation, either Badger.db or Level.db

## Goals

- Evaluate existing V0 Keybase functionality using the CLI as well as industry approaches documented above
- Determine what can be imported into V1 and where Pocket-specific Utility needs to be applied
- Determine which filesystem.db should be used from options documented above
- Build a functional mini-keybase that can create, delete, import, export, and list and show actor keys 
- Document the functionality and key architecture of the mini-keybase

## Deliverables

- [ ] https://github.com/pokt-network/pocket/issues/150 
- [ ] https://github.com/pokt-network/pocket/issues/204
- [ ] https://github.com/pokt-network/pocket/issues/205

## Non-goals / Non-deliverables

- Integrating Keybase with the CLI or other parts of the codebase 
- Implementing multisig 

---

**Creator**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
@Olshansk keybase bounty parent task for your review

**Comment by h5law** [comment]
Am ready to take this up if that's cool. I began work on this over the weekend in the `keybase_implementation` branch of the repo ;)

**Comment by jessicadaugherty** [comment]
Perfect, thank you @h5law! I had originally planned this epic so that the initial implementation of the keybase was coupled with Creating and Deleting keys. Does that work for you?

Let me know if it would be helpful to create one or more separate tickets to cover the initial research and keybase build? Or should we just use this parent ticket to track everything and I'll bring in the tickets mentioned in deliverables when they are in progress? Happy to make break anything down further if needed.

**Comment by h5law** [comment]
>I had originally planned this epic so that the initial implementation of the keybase was coupled with Creating and Deleting keys. Does that work for you?

@jessicadaugherty So I actually looked through all of the 3 "sub-issues" and my current code implements all of their features (excluding documentation). I have posted a `[WIP]` PR for review as there are still some issues in the code.

First is importing keys created with `wallet.pokt.network` in JSON format (and importing the V1 JSON keys into V0) as these _should_ be interoperable. However the V0 keys generate longer JSON armours 🤔 I am looking into this.

And the other main thing is around signatures - the usages listed in this doc _should_ work in theory as my implementation supports signing arbitrary `[]byte` messages and verifying them. But I don't have the knowledge around multisig to know if it follows the same process. I see that V0 CLI has the option to make a multi-sig account - this is not a feature currently (also is not in the goals of the issues) but I think its important to note where this implementation is not 100% "complete" (as anything can be)

However, creation, delete, show, list, get public key, get private key, sign, verify, check exists, some others are fully working and covered by tests. I think @Olshansk is reviewing it today/tomorrow.

Please let me know if this is doesn't answer what you said 🤣  Or if there are any other features you want me to get in there!

PS: No CLI implementation has been attempted. This is purely the "backend" that the CLI would interact with - the DB layer, interfaces etc

**Comment by jessicadaugherty** [comment]
> and my current code implements all of their features (excluding documentation)

Oh, amazing! I'll mark all 3 of these as "In Progress" in that case but keep this parent ticket in the iteration.

> First is importing keys created with wallet.pokt.network in JSON format (and importing the V1 JSON keys into V0) as these should be interoperable. However the V0 keys generate longer JSON armours 🤔 I am looking into this.

Makes sense. I wonder if the longer key generation is related to hex vs. base64 in ed25519?

> But I don't have the knowledge around multisig to know if it follows the same process. I see that V0 CLI has the option to make a multi-sig account - this is not a feature currently (also is not in the goals of the issues) but I think its important to note where this implementation is not 100% "complete" (as anything can be)

Great callout/feedback. I will adjust the ticket(s) to make it clear that multi-sig functionality is out of scope for this ticket. And create a follow up issue :)

> However, creation, delete, show, list, get public key, get private key, sign, verify, check exists, import/export (priv string) [V0<->V1 ✅ ], import/export (JSON string) [V1<->V1 ✅ V0<->V1 ❌ ], some others are fully working and covered by tests.

*chefs kiss*

> PS: No CLI implementation has been attempted. This is purely the "backend" that the CLI would interact with - the DB layer, interfaces etc

That's perfect. I have a WIP draft that will cover that integration when we get through the initial build here. I'll update the ticket(s) to note that this is out of scope too. 

Thank you so much @h5law!

**Comment by h5law** [comment]
> Makes sense. I wonder if the longer key generation is related to hex vs. base64 in ed25519?

@jessicadaugherty <3 I will look into this 

> Thank you so much

Anytime this task was a fun one! Looking forward to seeing it all the way through 🚀

**Comment by h5law** [comment]
@jessicadaugherty ❤️ Turns out the JSON issue was related to functions in the `ed25519` library used by V0 that are different in V1. The encoding in V0 of the private key when being encrypted follows some _unnecessary_ conversion steps. This however I decided could be done better but by doing it in  a cleaner way the encoded strings are different lengths.

I have just pushed a commit that changes this can can confirm V0-V1 import export is fully functional with JSON and raw priv strings 😉

**Comment by jessicadaugherty** [comment]
LFG @h5law!!! Nicely done. Tysm!

**Comment by Olshansk** [comment]
### Major items in existing PR
- [ ] We need to add some documentation. Just the MVR (Minimum Viable Readme): you should be able to port a lot of the text in the description
- [ ] Code organization - move the relevant logic into `crypto`
- [ ] I’d like to understand the decision for the choice of `nonce` (we can discuss inline)
- [ ] Left a few comments with a `ditto` so please apply everywhere

---

### Follow-Up Tasks
- [ ] 1. Integrate with the CLI.
- [ ] 2. Add support for threshold sigs in the crypto library.

---

Re 1 - @deblasis was kind enough to leave a lot of comments, so if you search for #150 in the codebase, you’ll find all the appropriate entry points. @jessicadaugherty, could you help create a ticket that captures the necessary work to incorporate the keybase into the CLI?

---

Re 2 - Rather than multisigs, let’s go with **threshold sigs**! It’s what everyone wants in the context of governance anyhow, and we’ll be able to reuse it in the consensus library when we add support for DKG (cc @gokutheengineer ).

❓  Last I checked, I couldn't find a good threshold sig library. Part of the ticket should evaluate if a non-interactive threshold sig library is even available (it might only be possible with BLS if we don't have DKG), and decide if we should go with a multi-sig library instead, which are more readily available. Let's create the ticket and start the discussion there.

✍️  It'll affect how we do verification of signed messages, but I don't think the keybase specifically will need special support for it. For both threshold sigs and multisigs, the user still only has access to their own key and not the others.

---

#### Bonus

🏗️  CC @okdas for context that our keybase uses badgerDB. One day (distant day), we might have other backends (similar to what [cosmos does](https://github.com/cosmos/cosmos-sdk/tree/main/crypto)) with real key management systems.

---

#### Extra Bonus
🌕  Also CCing @roshanr95 from Marlin protocol who are focusing a lot of enclaves. There is no immediate AI, but if we want pocket operators to work with secure enclaves, there will need to be som thought put into change sin the keybase.

**Comment by Olshansk** [comment]
We have found the 🔑
