### ISSUE TITLE
[Tooling] CI not running tests on CI-generated commits

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#900]
## Objective

Ensure commits added by CI actions cause CI tests to run and prevent merging in the event of failure.

## Origin Document

![image](https://github.com/pokt-network/pocket/assets/600733/22a5dad1-919d-4344-8464-8bdf7e6d7112)

## Goals

- Prevent PRs which contain failing tests from being merged unintentionally.

## Deliverable

- Update relevant CI logic

## Non-goals / Non-deliverables

- ...

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

1. Open a test PR using a branch based on the fix branch which:
  - applies the "do not merge" label
  - modifies a helm chart and/or values such that helm docs are generated by CI
  - contains a linter violation; e.g., ignore an error or define an unused variable:
    ```go
    var x string    
    ```
  - contains a unit test failure; e.g., add a new test that always fails:
    ```go
    func TestSanity(t *testing.T) {
      t.Fatal()
    }
    ```
  - contains an E2E test failure; :sweat_smile: (optional)
2. Ensure CI fails for the generated commit due to the label, linter, and unit test failure (ideally, E2E failure as well).

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
- [ ] **k8s LocalNet**: verify a `k8s LocalNet` is still functioning correctly by following the instructions [here](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md)

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @okdas

**Comment by okdas** [comment]
Unfortunately, this is done on purpose by GitHub: https://github.com/orgs/community/discussions/25702
Options are:
- Switch to Personal Access Tokens (for example, my GitHub user or another user we can specifically register just for that, but we'd have to pay for the seat).
- Do nothing, but whenever such a commit is created, we can manually trigger a workflow in the GitHub UI.
- Set up a Helm job to fail when the documentation is not updated instead of pushing a fix. That particular job for Helm was set up for convenience, but we can change the configuration.

I'm personally leaning towards manually kicking the job off because I don't want other team members to feel like they have to know Helm and other tooling used for infrastructure. And having that job removes another roadblock for passing CI gates. I also do not like the idea of using PAT for authentication.

Here is how the job can be kicked off:

![image](https://github.com/pokt-network/pocket/assets/4950477/8eabd48f-9114-4732-812f-433be433d07b)

Please let me know what you think!

**Comment by okdas** [comment]
Duh, after playing around, it doesn't appear that the manual trigger is an option because it runs the job against the branch, and not the PR. As a result, this job doesn't trigger the e2e tests because we only run them when the label is attached to the **pull request**. That said, pushing an empty commit is still an option!

**Comment by Olshansk** [comment]
> Duh, after playing around, it doesn't appear that the manual trigger is an option because it runs the job against the branch, and not the PR. As a result, this job doesn't trigger the e2e tests because we only run them when the label is attached to the **pull request**. That said, pushing an empty commit is still an option!

https://github.com/pokt-network/pocket/pull/908

**Comment by Olshansk** [comment]
Closing this out per the helper created above + discussion.
